### ISSUE TITLE
Output side state

### ISSUE THREAD

**Issue by geezIIT** [geez0x1/CompliantJointToolbox#12]
The output side state is currently named q_b (for 'bar'). However perhaps to be more standard we can rename this to q_l (for 'load'). @joernmalzahn Agreed?

**Comment by geez0x1** [comment]
This has been decided and will be changed as proposed.

**Comment by geez0x1** [comment]
Done in commits:
6c67ab6afb67ce6a1cfa9425b6027726c95f0b69
1f3a4fa22aecd09350f187c41cf1e268635f8b49
f1167f9d7ed61ecd20f3a7ad2e2e0a1267e14ba9
