### ISSUE TITLE
Tag v0.2

### ISSUE THREAD

**Issue by geez0x1** [geez0x1/CompliantJointToolbox#14]
@joernmalzahn I would like the current state (with datasheetgenerator, before additional features) as v0.2. Agreed?

**Comment by geez0x1** [comment]
@joernmalzahn It would be good to resolve #15 first though. I have no idea where to start, can you do it?

**Comment by joernmalzahn** [comment]
Does not look simple. Having a hard time to reproduce it. It might be a Simulink Version Issue. Will take some time, but I do agree, we have to fix this.

**Comment by geez0x1** [comment]
v0.2 tagged: I has a lot of new features and improvements compared to v0.1, and it doesn't seem like we can consistently produce #15, let alone resolve it for now.
