### ISSUE TITLE
Unit Test for Symbolics Generation Breaks

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#22]
New parameters for ripple model break unit test for symbolics generation.

**Comment by joernmalzahn** [comment]
This issue was fixed in 48f87a2

Actually all unit tests broke... the addition of spring damping broke the genericJoint test.
Renaming of the linear models broke the jointBuilder tests.
Those tests are adjusted now.

**Comment by geez0x1** [comment]
Oops! My bad. Thanks for fixing.
