### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#24]
We have just very few not well documented examples. We should improve that.

**Comment by joernmalzahn** [comment]
We have a nice little gui now, that allows a user to select examples stored in examples/matlab and examples/simulink. The gui automatically looks for existing examples.

The gui lets you open and run an example. The description of the example is shown directly in the gui.

We just need to implement some examples now.

**Comment by geez0x1** [comment]
WiP in `dev_doc` branch. Separate issues are tracking the progress of this so closing (since it's not actually an 'issue' so much)
