### ISSUE TITLE
Empty defaults of ripple models break Simulink block execution.

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#25]
When running a Simulink model with a joint block (e.g. full_dyn), the following error message appears:

 Parse error: Expression or statement is incomplete or incorrect.

Function 'JointModel/nonLinDynamicsFcn' (#57.752.753), line 31, column 20:
";"
Launch diagnostic report.
Component: MATLAB Function | Category: Coder error

**Comment by geezIIT** [comment]
I fixed this in a slightly nicer way, where it simply prints empty arrays like the original parameters when no ripple sources are specified. Thanks for finding the bug.
