### ISSUE TITLE
Coulomb smoothness function using tanh

### ISSUE THREAD

**Issue by geez0x1** [geez0x1/CompliantJointToolbox#30]
We're currently using `atan(1000 * v) / (pi/2)`; using `tanh(500 * v)` is cleaner, gives approximately the same slope around `v=0` and is a function that goes to exactly -1/+1 within reasonable values of `v`.

**Comment by joernmalzahn** [comment]
No objections from my side.

**Comment by geez0x1** [comment]
Fixed in 3634534a92af612fb3b7de9305b1f7a4b3cd7513.
