### ISSUE TITLE
getFFt produces an output but no error for sig and t being unequal length

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#33]
It is possible to call getFFt with a time and signal vector of different lengths. 
However, the output is not clear in this case. Likely the user has done a mistake when this happens and an error should be issued.

**Comment by joernmalzahn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [getFFt produces an output but no error for sig and t being unequal length](https://trello.com/c/Owu9jNvZ/2-getfft-produces-an-output-but-no-error-for-sig-and-t-being-unequal-length)

**Comment by geez0x1** [comment]
@joernmalzahn What's that?

**Comment by geez0x1** [comment]
Fixed in 66e1784c607f3a94d895900a492062745564c499.
