### ISSUE TITLE
Gearbox ratio in electric subystem models 

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#34]
The file electric_dyn_zero_inductance.m includes the transmission ratio.
The model implemented in electric_dyn.m does not.

Hence the two electric dynamics models have different outputs. This shall not be.

**Comment by joernmalzahn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix gearbox ratio in electric subystem](https://trello.com/c/jhWdeWv9/1-fix-gearbox-ratio-in-electric-subystem)

**Comment by geez0x1** [comment]
Fixed in 587c5516e5bbb2e0c6a909bb3de9a32a3f60df67. Not closing yet, as that branch is not merged.

**Comment by geez0x1** [comment]
What was also missing was a factor 1/L for the q_m_dot input element in the B matrix.
