### ISSUE TITLE
Nonlinear torques are not added in the right way in the state-space structure

### ISSUE THREAD

**Issue by VishnuDevA7** [geez0x1/CompliantJointToolbox#35]
The torques from the nonlinear model has to be multiplied with a suitable gain matrix in order to be added to the states

**Comment by geez0x1** [comment]
Nice find :) Fixed in 40d092765bcdc5090b6f07a8eecda801c9a2974c by (ab)using the B matrix inside the block (which saves generating a properly-dimensioned matrix):

`B(:,1) / (k_t * n)`

**Comment by geez0x1** [comment]
I just realised my fix is incomplete. Let me work on it some more.

**Comment by geez0x1** [comment]
Correct fix in 07557ad. Building `B_nonlinear` in the block mask as follows:
`B_nonlinear = [zeros([size(I,1),1]); 1./diag(I)];`
which changes size depending on the size of `I` and thus on the chosen model.

**Comment by geez0x1** [comment]
@VishnuDevA7 Can you confirm this is fixed for you?

**Comment by VishnuDevA7** [comment]
Yes, its fixed :)
