### ISSUE TITLE
MATLAB library backwards compatiblity

### ISSUE THREAD

**Issue by geezIIT** [geez0x1/CompliantJointToolbox#36]
**This is a copy of the original issue in another repo. This is a more appropriate place.**

MATLAB will not (at all, or with complaints after changing some settings) open Simulink library files created in newer versions of MATLAB/Simulink. Case in point (using R2017a):

![screenshot from 2018-03-19 15-01-55](https://user-images.githubusercontent.com/7579312/37600115-a8edba40-2b86-11e8-95aa-c06bcb619ec2.png)

Similarly, I cannot open any of the `cjt_library_*.mdl` files in the `dev_doc` branch.

**Comment by geezIIT** [comment]
I had a look around the internet (lots of questions about this). I was hoping to find some model property which we could set to force the file sticking to a certain version (e.g. R2016a), but that doesn't appear to exist.

Unchecking the following checkbox does allow me to load the file, although correct functioning is not guaranteed:
![screenshot from 2018-03-26 12-05-20](https://user-images.githubusercontent.com/7889615/37900290-12e2325c-30ee-11e8-800b-51959764eccc.png)
with the following warnings:
![screenshot from 2018-03-26 12-04-20](https://user-images.githubusercontent.com/7889615/37900303-1918df40-30ee-11e8-8603-6ee91500b641.png)

So I'd like to stress that we should save in a compatible way, to avoid such errors. I propose we write a script that checks and if necessary resaves library files in a compatible version, I'm fairly sure that's doable from a script.

**Comment by geezIIT** [comment]
Resources:
https://it.mathworks.com/help/simulink/slref/save_system.html
https://stackoverflow.com/questions/42033503/how-to-standardize-simulink-mdl-file-saving-method-in-a-source-controlled-projec (useful while we're at it)
https://it.mathworks.com/help/simulink/slref/simulink.exporttoversion.html#bu5axol-4
https://it.mathworks.com/help/simulink/ug/saving-a-model.html

**Comment by geezIIT** [comment]
In the latest commit in `dev_doc` I have added a file `saveCompatible.m`; it contains a list of essential library files (currently incomplete), checks their `SimulinkVersion`, and if that isn't 8.7 (R2016a), re-saves them. It works quite well.

Perhaps we can expand this to a `prepareRelease.m`, which is ran before merging and tagging new releases on master.

Thoughts?

**Comment by joernmalzahn** [comment]
Nice work Wes. 

I think the automation is the only way to practically deal with the backwards compatibility mess. During block development it seems rather impossible to remain backwards compatible (involves too many clicks...). However, as a final stage before merging a dev branch into the master it could be conceivable . 

A release preparation toolkit makes sense, also in general.

**Comment by geez0x1** [comment]
I've just updated `saveCompatible.m` to include the new examples. Also, I've updated a few other files in the Simulink examples (openLoop.mdl, openLoop_inputFromFile.mdl and controlBlockDevelopment_generic.mdl) to correctly reference the new CJT library files.

@joernmalzahn Perhaps we can include this in the paper version of the paper? Being at least a bit backwards compatible is important imo.

**Comment by joernmalzahn** [comment]
You mean to mention our effort for backwards compatibility in the paper?

**Comment by geez0x1** [comment]
No I mean to ensure that the version committed for the paper (both on Github and Code Ocean) are backwards compatible and identical.

**Comment by joernmalzahn** [comment]
Ok, that's no big deal.

**Comment by geez0x1** [comment]
This works and is used.
