### ISSUE TITLE
Clean up (remove) old parameter files

### ISSUE THREAD

**Issue by geez0x1** [geez0x1/CompliantJointToolbox#48]
The following parameter files are mostly outdated and can be removed in my opinion, from the `dev_doc` branch that will be mainlined in the foreseeable future.

- B11
- B12
- CE_Big
- WMBig10k
- WMBig10k_ds
- WMBig2300_ds

@joernmalzahn : Would you agree?

**Comment by geez0x1** [comment]
@joernmalzahn It would be great if you could fix #38, so when we 'really' release the toolbox we have clean parameter files with it.

**Comment by geez0x1** [comment]
5ad23f4

**Comment by geez0x1** [comment]
Reopening and reverted in 5589953b924bfb32ecc0f9878bc1c1b8900e1569; most current unit tests still depend on the old parameter files which blocks removing them.

**Comment by joernmalzahn** [comment]
old parameter files removed, the only remaining issue now is the first test for the simulink library. It crashes because of the newly introduced second sampling time for the electrical subsystem.

**Comment by joernmalzahn** [comment]
Closing this one and opened new one #51 for the remaining issue.
