### ISSUE TITLE
Unit test for electrical subsystem block fails

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#51]
After removing the old parameter files and introducing the new CJT-ones in the unit tests, this test fails due to sampling time clash with the newly introduced electrical sampling time Ts_elec:

cjtSimulinkLibraryTest/testBuiltJoint

**Comment by geez0x1** [comment]
The problem appears to lie in the model settings; the test you referenced as an example, `cjtSimulinkLibraryTest/testBuiltJoint`, references a file `simulinkBlockLibraryTest.mdl`, which had a setting enabled on the solver page called **"Treat each discrete rate as a separate task"**.

As far as I can tell, this is a non-standard option (it is off for me for new Simulink models), which is also only available on discrete-time solvers. Disabling it results in the model running, albeit with a algebraic loop on which I'll create another issue.
