### ISSUE TITLE
Kalman observer and Luenberger observer do not find stable gains

### ISSUE THREAD

**Issue by joernmalzahn** [geez0x1/CompliantJointToolbox#53]
Both, the Kalman block and the Luenbeger block throw this error when inserting the joint class parameter:

![grafik](https://user-images.githubusercontent.com/10830038/42629972-848d3a50-85d5-11e8-9254-9bc352165603.png)

The guess is that the blocks have not been updated after recent interface changes (input / output dimensionality). This way the blocks are unusable.

**Comment by joernmalzahn** [comment]
I created a new branch to work on this issue: 
https://github.com/geez0x1/CompliantJointToolbox/tree/dev_fix_issue_53 

In the meantime, I disabled both in the dev_doc branch.

**Comment by geez0x1** [comment]
Leaving a note here to say that the tests in `cjtSimulinkLibraryTest` need to be re-enabled once this is fixed.

**Comment by geez0x1** [comment]
This is an interesting issue. The systems used in the examples (`output_fixed`) are not observable due to the secondary input.

**Comment by geez0x1** [comment]
This has been fixed by somewhat of a workaround for the Kalman observer, and properly for the Luenberger observer. Both examples and unit tests work now: b6819be16f3a01ada97b4e49b54c416c9d4e20d1...c5b0095f29442c74fc8b436ce251762a8bc2bc7b.
