### ISSUE TITLE
Removal of _no_friction models

### ISSUE THREAD

**Issue by geez0x1** [geez0x1/CompliantJointToolbox#66]
The _no_friction models serve very little purpose in my opinion; they can be just as easily achieved by setting the friction parameters to zero in a parameter file or the built joint. Additionally, the nonlinear dynamics models do not currently support these models. Hence, I would suggest removing them.

@joernmalzahn Please let me know whether you agree.

**Comment by geez0x1** [comment]
@joernmalzahn ?

**Comment by joernmalzahn** [comment]
Fine with me.

**Comment by geez0x1** [comment]
Done
