### ISSUE TITLE
genericJoint::draw_speed_torque_curve() needs work

### ISSUE THREAD

**Issue by geez0x1** [geez0x1/CompliantJointToolbox#8]
The function `genericJoint::draw_speed_torque_curve()` is poorly documented and contains magic numbers. It should either become a tool (in `tools/`) or properly developed if it is to be part of `genericJoint`.

**Comment by geez0x1** [comment]
@joernmalzahn: AFAIK this is now removed from genericJoint. Correct?

**Comment by joernmalzahn** [comment]
This function has been removed from the generic joint class, yes. There is a new dataSheetGenerator class that handels torque speed curve generation and more things now.
